Repository hypothesis/report, pull requests merged in 2022-12, with the labels that each got.

#109 Add the SQL tutorial from Sparky
  docs/tutorials/sql_tips_and_tricks/00_overview.md
  docs/tutorials/sql_tips_and_tricks/01_slicing_dates.md
  docs/tutorials/sql_tips_and_tricks/02_unions.md
  docs/tutorials/sql_tips_and_tricks/03_subqueries.md
  docs/tutorials/sql_tips_and_tricks/04_common_table_expressions.md
  docs/tutorials/sql_tips_and_tricks/05_selecting_fixed_values.md
  docs/tutorials/sql_tips_and_tricks/06_cumulative_values_window_functions.md
  docs/tutorials/sql_tips_and_tricks/07_approximate_queries.md
  docs/tutorials/sql_tips_and_tricks/08_anti_joins.md
  docs/tutorials/sql_tips_and_tricks/09_recursive_queries.md
  docs/tutorials/sql_tips_and_tricks/10_metabase_fanciness.md
Labels: documentation

#128 Fix some copy paste errors in the view shim for LMS
  report/data_tasks/report/create_from_scratch/05_rename_shim/02_lms_shim.sql
Labels: bug

#130 Move existing views into product specific schema
  report/data_tasks/report/create_from_scratch/03_h/01_authorities/01_create_view.sql
  report/data_tasks/report/create_from_scratch/03_h/01_authorities/02_initial_fill.sql
  report/data_tasks/report/create_from_scratch/03_h/02_authority_activity/01_create_view.sql
  report/data_tasks/report/create_from_scratch/03_h/02_authority_activity/02_initial_fill.sql
  report/data_tasks/report/create_from_scratch/04_lms/01_organization/01_create_view.sql
  report/data_tasks/report/create_from_scratch/04_lms/01_organization/02_initial_fill.sql
  report/data_tasks/report/create_from_scratch/04_lms/02_organization_activity/01_create_view.sql
  report/data_tasks/report/create_from_scratch/04_lms/02_organization_activity/02_initial_fill.sql
  report/data_tasks/report/create_from_scratch/04_lms/03_events/01_create_view.sql
  report/data_tasks/report/create_from_scratch/04_lms/03_events/02_initial_fill.sql
  report/data_tasks/report/create_from_scratch/05_rename_shim/01_h_shim.sql
  report/data_tasks/report/create_from_scratch/05_rename_shim/02_lms_shim.sql
  report/data_tasks/report/create_from_scratch/99_hubspot_write/01_company_property_update/01_create_view.sql
  report/data_tasks/report/create_from_scratch/99_remove_old_views.sql
Labels: technical debt

#132 Update the refresh scripts to work with the new schema
  report/data_tasks/report/refresh/02_h/01_materialized_views_refresh.sql
  report/data_tasks/report/refresh/03_lms/01_materialized_views_refresh.sql
Labels: bug

#133 Pass through groups and counts to Report
  report/data_tasks/report/create_from_scratch/00_schema/04_create_fdw_schema_lms.jinja2.sql
  report/data_tasks/report/create_from_scratch/04_lms/04_groups/01_groups/01_create_view.sql
  report/data_tasks/report/create_from_scratch/04_lms/04_groups/01_groups/02_initial_fill.sql
  report/data_tasks/report/create_from_scratch/04_lms/04_groups/02_group_map/01_create_view.sql
  report/data_tasks/report/create_from_scratch/04_lms/04_groups/02_group_map/02_initial_fill.sql
  report/data_tasks/report/create_from_scratch/04_lms/04_groups/03_group_bubbled_activity/01_create_view.sql
  report/data_tasks/report/create_from_scratch/04_lms/04_groups/03_group_bubbled_activity/02_initial_fill.sql
  report/data_tasks/report/refresh/03_lms/01_materialized_views_refresh.sql
Labels: technical enabler

#136 Change our version of alpine to match the version in Metabase
  .cookiecutter/cookiecutter.json
  .python-version
  Dockerfile
  bin/make_python
Labels: bug

#137 Complete list of env vars in docker compose
  docker-compose.yml
Labels: technical debt
